#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"

grep -q "AI factory" "$ROOT/docs/ai-factory.md"
grep -q "Company-style pane operating model" "$ROOT/docs/company-operating-model.md"
grep -q "Batch version-management system" "$ROOT/docs/version-management.md"
grep -q "Batch PR train" "$ROOT/docs/version-management.md"
grep -q "Workers create evidence and commits; the release train creates PRs" "$ROOT/docs/version-management.md"
grep -q "Batch outcome" "$ROOT/templates/TEAM_PLAN.md"
grep -q "Acceptance checklist" "$ROOT/templates/TEAM_PLAN.md"
grep -q "Role roster" "$ROOT/templates/TEAM_PLAN.md"
grep -q "Version / PR train" "$ROOT/templates/TEAM_PLAN.md"
grep -q "Pane Role Charter" "$ROOT/templates/ROLE_CHARTER.md"
grep -q "Batch Version / PR Train Board" "$ROOT/templates/BATCH_VERSION_PLAN.md"
grep -q "worker branches and small commits are integrated into the batch branch" "$ROOT/templates/BATCH_VERSION_PLAN.md"
grep -q "codex-tasks/blockers.txt" "$ROOT/docs/ai-factory.md"
grep -q "csup factory-audit" "$ROOT/docs/ai-factory.md"
grep -q "csup staff" "$ROOT/docs/ai-factory.md"
grep -q "csup factory-run" "$ROOT/docs/ai-factory.md"
grep -q "reason=no_queued_work" "$ROOT/docs/ai-factory.md"
grep -q "docs/company-operating-model.md" "$ROOT/docs/ai-factory.md"
grep -q "docs/version-management.md" "$ROOT/docs/ai-factory.md"
grep -q "docs/worker-communication.md" "$ROOT/docs/ai-factory.md"
grep -q "meeting_sheet.md" "$ROOT/docs/worker-communication.md"
grep -q "journals/<lane>.md" "$ROOT/docs/worker-communication.md"
grep -q "Lock before shared writes" "$ROOT/docs/worker-communication.md"
grep -q "Context-size limits" "$ROOT/docs/worker-communication.md"
grep -q "TEAM_PLAN.md.*under 200 lines" "$ROOT/docs/worker-communication.md"
grep -q "meeting_sheet.md.*under 120 lines" "$ROOT/docs/worker-communication.md"
grep -q "journals/<lane>.md.*under 120 lines" "$ROOT/docs/worker-communication.md"
grep -q "Communication and write-lock table" "$ROOT/templates/TEAM_PLAN.md"
grep -q "Keep this file under 200 lines" "$ROOT/templates/TEAM_PLAN.md"
grep -q "Keep this file under 120 lines" "$ROOT/templates/MEETING_SHEET.md"
grep -q "Keep each lane journal under 120 active lines" "$ROOT/templates/JOURNAL_ENTRY.md"
grep -q "Use this file for cross-lane communication" "$ROOT/templates/MEETING_SHEET.md"
grep -q "Lane journal template" "$ROOT/templates/JOURNAL_ENTRY.md"
grep -q "docs/gm-staffing.md" "$ROOT/docs/parallel-sessions/general-manager.md"
grep -q "Continuous monitoring and reflection" "$ROOT/docs/parallel-sessions/general-manager.md"
grep -q "journals/gm.md" "$ROOT/docs/parallel-sessions/general-manager.md"
grep -q "benefit" "$ROOT/docs/parallel-sessions/general-manager.md"
grep -q "journals/gm.md" "$ROOT/docs/worker-communication.md"
grep -q "Keep GM reflection entries short" "$ROOT/docs/parallel-sessions/general-manager.md"
grep -q "csup staff <project>" "$ROOT/docs/gm-staffing.md"
grep -q "Staffing ledger" "$ROOT/templates/TEAM_PLAN.md"
grep -q "VERSION_BOARD.md" "$ROOT/docs/ai-factory.md"
grep -q "docs/blocker-schema.md" "$ROOT/docs/ai-factory.md"
grep -q "docs/blocker-schema.md" "$ROOT/docs/system-governor.md"
grep -q "VERSION_BOARD.md" "$ROOT/docs/system-governor.md"
grep -q "type=code|data|approval|infra|empirical|external" "$ROOT/docs/blocker-schema.md"
grep -q "docs/ai-factory.md" "$ROOT/docs/parallel-sessions.md"
grep -q "fixed-management" "$ROOT/docs/parallel-sessions.md"
grep -q "docs/version-management.md" "$ROOT/docs/parallel-sessions.md"
grep -q "VERSION_BOARD.md" "$ROOT/docs/parallel-sessions.md"
grep -q "GM is a real Codex session" "$ROOT/docs/parallel-sessions.md"
grep -q "actively reviews the latest manager reports" "$ROOT/docs/parallel-sessions/general-manager.md"
grep -q "communicates project direction back to managers" "$ROOT/docs/parallel-sessions/general-manager.md"
grep -q "csup gm-start <project>" "$ROOT/docs/parallel-sessions.md"
grep -q "Every active project should have three fixed panes" "$ROOT/docs/parallel-sessions.md"
grep -q "Managers report to GM" "$ROOT/docs/parallel-sessions/general-manager.md"
grep -q "Every active team must have at least" "$ROOT/docs/parallel-sessions/general-manager.md"
grep -q "Every active team has a reviewer" "$ROOT/docs/ai-factory.md"
grep -q "Workspace contract" "$ROOT/docs/parallel-sessions/reviewer.md"
grep -q "docs/worker-communication.md" "$ROOT/docs/parallel-sessions/reviewer.md"
grep -q "fixed-review" "$ROOT/templates/TEAM_PLAN.md"
grep -q "fixed-executive" "$ROOT/templates/TEAM_PLAN.md"
grep -q "fixed-executive" "$ROOT/templates/ROLE_CHARTER.md"
grep -q "templates/TEAM_PLAN.md" "$ROOT/docs/parallel-sessions/validator-planner.md"
grep -q "templates/BATCH_VERSION_PLAN.md" "$ROOT/docs/parallel-sessions/validator-planner.md"
grep -q "DRI" "$ROOT/docs/parallel-sessions/validator-planner.md"
grep -q "codex-tasks/blockers.txt" "$ROOT/docs/parallel-sessions/validator-planner.md"
grep -q "TEAM_PLAN.md" "$ROOT/docs/parallel-sessions/dynamic-worker.md"
grep -q "VERSION_BOARD.md" "$ROOT/docs/parallel-sessions/dynamic-worker.md"
grep -q "docs/company-operating-model.md" "$ROOT/docs/parallel-sessions/dynamic-worker.md"
grep -q "codex-tasks/blockers.txt" "$ROOT/templates/TEAM_PLAN.md"
grep -q "Self-steering and role recycling" "$ROOT/docs/ai-factory.md"
grep -q "csup steward <project>" "$ROOT/docs/ai-factory.md"
grep -q "Toyota / Japanese kaizen, kanban, and andon" "$ROOT/docs/company-operating-model.md"
grep -q "Dynamic role reassignment" "$ROOT/docs/company-operating-model.md"
grep -q "Empty-queue need discovery" "$ROOT/docs/parallel-sessions/dynamic-worker.md"
grep -q "csup steward <project> --sample-secs=30" "$ROOT/docs/parallel-sessions/validator-planner.md"

echo "ok: AI factory docs require GM session, measured staffing, manager-owned teams, blocker-first queues, role recycling, and factory-run"
